- name: download Ant
  get_url: |
    url=http://ftp.tsukuba.wide.ad.jp/software/apache//ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz
    dest={{ src_dir }}
  tags: ant

- name: unarchive the compressed Ant binaries
  unarchive: "copy=no src={{ src_dir }}/apache-ant-{{ ant_version }}-bin.tar.gz dest={{ install_path }} creates=/usr/local/apache-ant-{{ ant_version }}"
  tags: ant

- name: update the symbolic link to the Ant install
  file: "path={{ install_path }}/ant src={{ install_path }}/apache-ant-{{ ant_version }} state=link force=yes"
  tags: ant

- name: create the symbolic link to the Ant binary
  file: "path={{ command_path }}/ant src={{ install_path }}/ant/bin/ant state=link"
  tags: ant

- name: set ANT_HOME environment variable
  lineinfile: dest=/etc/environment regexp='^ANT_HOME.*' line='ANT_HOME={{ install_path }}/ant' insertbefore='^PATH.*'
  tags: ant
