- name: package install
  yum: pkg={{ item }} state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel 
    - zlib-devel
    - perl-ExtUtils-MakeMaker
 
- name: git install
  vars:
    git_version: 2.8.2
  include: git.yml

- name: java install
  vars:
    java_version: 1.8.0
  include: java.yml
