- name: yum install
  yum: pkg={{ item }} state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel 
    - zlib-devel
    - perl-ExtUtils-MakeMaker
 
- name: git install
  vars:
    src_dir: /usr/local/src
    git_install_path: /usr/local
    git_version: 2.7.1
  include: git.yml
