- name: てすと
  hosts: test
  tasks:
    - file: path=/tmp/ansible-test state=directory


#- name: deploy MySQL and configure the databases
#  hosts: dbservers
#  become: true
#  become_user: vagrant
#  roles:
#    - mysql
