- name: CentOSへのミドルウェアインストール
  hosts: centos
  become: yes
  gather_facts: no
  roles:
    - common

- name: deploy MySQL and configure the databases
  hosts: dbservers
  become: yes
  roles:
    - mysql

- name: sora deploy and start
  hosts: sora
  become: yes
  roles:
    - sbt
    - sora
