- name: CentOSへのミドルウェアインストール
  hosts: centos
  become: yes
  gather_facts: no
  roles:
    - common
    - sbt

- name: deploy MySQL and configure the databases
  hosts: dbservers
  become: yes
  roles:
    - mysql

- name: apply ShangriLa DDL/DML
  hosts: dbservers
  become: no
  roles:
    - shangrila

- name: sora deploy and start
  hosts: sora
  become: no
  roles:
    - sora
