- name: CentOSへのミドルウェアインストール
  hosts: centos
  become: yes
  gather_facts: no
  roles:
    - common
    - sbt

- name: install CI server
  hosts: ciservers
  become: yes
  roles:
    - jenkins
    - flyway

- name: install MySQL and configure the databases
  hosts: dbservers
  become: yes
  roles:
    - mysql
    - mysql/anime_admin_development

- name: deploy ShangriLa DDL/DML
  hosts: ciservers
  become: no
  roles:
    - shangrila

- name: deploy sora
  hosts: sora
  become: no
  roles:
    - sora
